2022-03-17 18:52:26.804 INFO  [acme.Launcher@main] Starting Launcher using Java 1.8.0_281 on LAPTOP-I3TOCOSF with PID 15192 (C:\Users\alvar\Desktop\Universidad\DP 2\Workspace-22.0\Frameworks\Acme-Framework-22.1\target\classes started by alvar in C:\Users\alvar\Desktop\Universidad\DP 2\Workspace-22.0\Projects\Acme-One-1.0) 
2022-03-17 18:52:26.806 DEBUG [acme.Launcher@main] Running with Spring Boot v2.4.2, Spring v5.3.3 
2022-03-17 18:52:26.808 INFO  [acme.Launcher@main] The following profiles are active: development,populator 
2022-03-17 18:52:30.185 DEBUG [org.apache.jasper.servlet.JasperInitializer@main] Initializing Jasper for context [application] 
2022-03-17 18:52:32.205 ERROR [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean@main] Failed to initialize JPA EntityManagerFactory: @OneToOne or @ManyToOne on acme.entities.Patronage.patron references an unknown entity: acme.roles.Patron 
2022-03-17 18:52:32.210 WARN  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.Patronage.patron references an unknown entity: acme.roles.Patron 
2022-03-17 18:52:32.281 ERROR [org.springframework.boot.SpringApplication@main] Application run failed at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.Patronage.patron references an unknown entity: acme.roles.Patron\nat org.hibernate.cfg.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:97): @OneToOne or @ManyToOne on acme.entities.Patronage.patron references an unknown entity: acme.roles.Patron
2022-03-17 18:52:32.284 ERROR [acme.Launcher@main] org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.Patronage.patron references an unknown entity: acme.roles.Patron\norg.hibernate.cfg.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:97): @OneToOne or @ManyToOne on acme.entities.Patronage.patron references an unknown entity: acme.roles.Patron 
2022-03-17 18:52:32.285 INFO  [acme.Launcher@main] The application log provides additional debugging messages! 
2022-03-17 18:52:33.296 DEBUG [acme.Launcher@main] Exit code = 1 
